from django.urls import path
from . import views
urlpatterns=[

    path("index",views.index,name="index"),
    path('register1' , views.register1,name='register1'),
    path("", views.register, name="register1"),
    path("login/", views.login, name="login"),
    path('login/login1', views.login1, name='login1'),
    path("logout", views.logout, name="logout"),
    path("login/index_google", views.index_google, name="index_google"),
    path('view/',views.view_project, name = 'view_project'),
    path('view/add/', views.add_project, name='add_project'),
    path('tasks', views.add_project_task, name='add_project_task'),
    path('milestones', views.add_project_milestones, name='add_project_milestones'),
    path('view_tasks',views.view_task, name = 'view_task'),
    path('view_milestones',views.view_milestone, name = 'view_milestone'),
    path('opportunities',views.add_oppurtunities, name = 'add_opportunities'),
    path('view_opportunities',views.view_oppurtunity, name = 'view_opportunities'),
    path('quotes', views.add_quote , name= 'add_quote'),
    path('view_quotes',views.view_quote , name = 'view_quote'),
    path('products' , views.add_product , name='add_product'),
    path('view_products' , views.view_product , name = 'view_product'),
    path('services' , views.add_service , name = 'add_service'),
    path('view_services' , views.view_service , name = 'view_service'),
    path('invoices' , views.add_invoice , name = 'add_invoice'),
    path('view_invoices' , views.view_invoice , name = 'view_invoice'),
    path('salesorder' , views.add_salesorder  , name ='add_salesorder'),
    path('view_salesorder' , views.view_salesorder , name= 'view_salesorder'),
    path('vendors', views.add_vendor , name= 'add_vendors'),
    path('view_vendors' , views.view_vendor , name = 'view_vendors'),
    path('purOrders' , views.add_purOrder, name = 'add_purOrder'),
    path('view_purOrders', views.view_purOrder, name = 'view_purOrder'),
    path('compaigns' , views.add_compaign , name = 'add_compaigns'),
    path('view_compaigns' , views.view_compaign , name = 'view_compaigns'),
    path('serviceContracts' , views.add_serviceContract, name = 'add_serviceContracts'),
    path('view_serviceContracts' , views.view_serviceContract , name = 'view_serviceContracts'),
    path('internalTickets' , views.add_internalTicket , name = 'add_internalTickets'),
    path('view_internalTickets' , views.view_internalTicket , name = 'view_internalTickets'),
    path('workOrders', views.add_workOrders , name = 'add_workOrders'),
    path('view_workOrders', views.view_workOrder , name = 'view_workOrders'),
    path('cases' , views.add_case , name = 'add_cases'),
    path('view_cases', views.view_case , name = 'view_case'),
    path('FAQ' , views.add_FAQ , name = 'add_FAQ'),
    path('view_FAQ' , views.view_FAQ , name = 'view_FAQ'),
    path('bookmarks' , views.add_bookmark , name = 'add_bookmarks'),
    path('view_bookmarks', views.view_bookmark , name = 'view_bookmarks'),
    path('employees' , views.add_employee , name = 'add_employees'),
    path('view_employees' , views.view_employee , name = 'view_employees'),
    path('printTemplate' , views.add_printTemplate , name = 'add_printTemplate'),
    path('view_printTemplate', views.view_printTemplate , name = 'view_printTemplate'),
    path('contacts' , views.add_contact , name = 'add_contacts'),
    path('view_contacts' , views.view_contact , name = 'view_contacts'),
    path('organizations' , views.add_organization , name = 'add_organizations'),
    path('view_organizations' , views.view_organization , name = 'view_organizations'),
    path('view/add/save_projects' , views.save_projects , name ='save_projects'),
    path('save_tasks', views.save_tasks, name='save_tasks'),
    path('save_milestones', views.save_milestones, name='save_milestones'),
    path('save_contacts', views.save_contacts, name='save_contacts'),
    path('save_organizations', views.save_organizations, name='save_organizations'),
    path('save_opportunities', views.save_opportunities, name='save_opportunities'),
    path('save_quotes', views.save_quotes, name='save_quotes'),
    path('save_services', views.save_services, name='save_products'),
    path('save_invoices', views.save_invoices, name='save_invoices'),
    path('save_sale_orders', views.save_sale_orders, name='save_sale_orders'),
    path('save_cases', views.save_cases, name='save_cases'),






]
