# Generated by Django 2.1.10 on 2019-07-18 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Started', 'Started'), ('New', 'New'), ('In Progress', 'In Progress'), ('Waiting for feedback', 'Waiting for feedback'), ('On hold', 'On hold'), ('Completed', 'Completed'), ('Delivered', 'Delivered')], max_length=100)),
                ('realted_to', models.CharField(max_length=100)),
                ('assigned_to', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('target_end_date', models.DateField()),
                ('actual_end_date', models.DateField()),
                ('opportunity_name', models.CharField(max_length=100)),
                ('contact_name', models.CharField(max_length=100)),
                ('budget', models.IntegerField()),
                ('project_url', models.URLField()),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=100)),
                ('progress', models.IntegerField(choices=[('20%', '20%'), ('40%', '40%'), ('50%', '50%'), ('70%', '70%'), ('90%', '90%'), ('100%', '100%')])),
                ('desc', models.TextField()),
            ],
        ),
    ]
