# Generated by Django 2.1.10 on 2019-07-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pro', '0002_auto_20190718_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='addprojects',
            name='progress',
            field=models.DecimalField(choices=[(20, 20), (40, 40), (50, 50), (70, 70), (90, 90), (100, 100)], decimal_places=2, default=0, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addprojects',
            name='project_url',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
