# Generated by Django 2.1.10 on 2019-07-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pro', '0003_auto_20190718_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Started', 'Started'), ('New', 'New'), ('In Progress', 'In Progress'), ('Waiting for feedback', 'Waiting for feedback'), ('On hold', 'On hold'), ('Completed', 'Completed'), ('Delivered', 'Delivered')], max_length=100)),
                ('realted_to', models.CharField(max_length=100)),
                ('assigned_to', models.CharField(max_length=100)),
                ('milestone_name', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=100)),
                ('workedHours', models.IntegerField()),
                ('progress', models.DecimalField(choices=[(20, 20), (40, 40), (50, 50), (70, 70), (90, 90), (100, 100)], decimal_places=2, max_digits=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('desc', models.TextField()),
            ],
        ),
    ]
