# Generated by Django 2.1.10 on 2019-07-23 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pro', '0004_addtasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddMilestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_name', models.CharField(max_length=100)),
                ('realted_to', models.CharField(max_length=100)),
                ('assigned_to', models.CharField(max_length=100)),
                ('milestone_date', models.DateField()),
                ('desc', models.TextField()),
            ],
        ),
    ]
