# Generated by Django 2.1.10 on 2019-07-23 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pro', '0005_addmilestone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('primary_email', models.EmailField(max_length=254)),
                ('office_phone', models.IntegerField()),
                ('mobile_phone', models.IntegerField()),
                ('home_phone', models.IntegerField()),
                ('dob', models.DateField()),
                ('organization', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('assigned_to', models.CharField(max_length=100)),
                ('contact_type', models.CharField(choices=[('Lead', 'Lead'), ('Customer', 'Customer'), ('Partner', 'Partner'), ('Analyst', 'Analyst'), ('Vendor', 'Vendor')], max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('reffered_by', models.CharField(max_length=100)),
                ('SLA_name', models.CharField(max_length=100)),
                ('portal_user', models.CharField(choices=[('Yes', 'Yes')], max_length=100)),
                ('support_start_date', models.DateField()),
                ('support_end_date', models.DateField()),
                ('country', models.CharField(choices=[('INDIA', 'INDIA'), ('UNITED STATES', 'UNITED STATES'), ('CHINA', 'CHINA'), ('AUSTRALIA', 'AUSTRALIA'), ('FRANCE', 'FRANCE')], max_length=100)),
                ('street', models.TextField()),
                ('postal_code', models.IntegerField()),
                ('desc', models.TextField()),
                ('image', models.ImageField(upload_to='pics')),
                ('linkedin_url', models.URLField()),
                ('fb_url', models.URLField()),
            ],
        ),
    ]
