# Generated by Django 2.1.10 on 2019-07-23 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pro', '0006_addcontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcontact',
            name='home_phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='addcontact',
            name='mobile_phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='addcontact',
            name='office_phone',
            field=models.BigIntegerField(),
        ),
    ]
