# Generated by Django 2.1.10 on 2019-07-23 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pro', '0007_auto_20190723_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addcontact',
            old_name='image',
            new_name='img',
        ),
    ]
