# Generated by Django 2.1.10 on 2019-07-23 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pro', '0008_auto_20190723_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcontact',
            name='img',
        ),
    ]
