# Generated by Django 2.1.10 on 2019-07-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pro', '0010_addcontact_imgg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcontact',
            name='imgg',
            field=models.ImageField(upload_to='pictures/'),
        ),
    ]
