# Generated by Django 2.1.10 on 2019-07-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pro', '0013_auto_20190723_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcontact',
            name='imgg',
            field=models.FileField(upload_to='pictures/'),
        ),
    ]
