# Generated by Django 2.1.10 on 2019-07-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pro', '0014_auto_20190723_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=100)),
                ('p_email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('p_phone', models.IntegerField()),
                ('employees', models.CharField(max_length=100)),
                ('industry', models.CharField(choices=[('Goverment', 'Goverment'), ('Transportation', 'Transportation'), ('Telecommunications', 'Telecommunications'), ('Utilities', 'Utilities'), ('Other', 'Other')], max_length=100)),
                ('revenue', models.IntegerField()),
                ('ownership', models.CharField(max_length=100)),
                ('SLA_name', models.CharField(max_length=100)),
                ('assigned_to', models.CharField(max_length=100)),
                ('sic_code', models.IntegerField()),
                ('billing_country', models.CharField(choices=[('INDIA', 'INDIA'), ('UNITED STATES', 'UNITED STATES'), ('CHINA', 'CHINA'), ('AUSTRALIA', 'AUSTRALIA'), ('FRANCE', 'FRANCE')], max_length=100)),
                ('shipping_country', models.CharField(choices=[('INDIA', 'INDIA'), ('UNITED STATES', 'UNITED STATES'), ('CHINA', 'CHINA'), ('AUSTRALIA', 'AUSTRALIA'), ('FRANCE', 'FRANCE')], max_length=100)),
                ('billing_address', models.TextField()),
                ('shipping_address', models.TextField()),
                ('billing_postal_code', models.IntegerField()),
                ('shipping_postal_code', models.IntegerField()),
                ('desc', models.TextField()),
                ('org_img', models.ImageField(upload_to='pictures')),
            ],
        ),
    ]
