# Generated by Django 2.1.10 on 2019-07-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pro', '0015_addorganization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addorganization',
            name='employees',
            field=models.IntegerField(),
        ),
    ]
