# Generated by Django 2.1.10 on 2019-07-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pro', '0016_auto_20190723_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addorganization',
            name='p_phone',
            field=models.BigIntegerField(),
        ),
    ]
