# Generated by Django 2.1.10 on 2019-07-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pro', '0018_auto_20190723_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCompaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=100)),
                ('close_date', models.DateField()),
                ('product', models.CharField(max_length=100)),
                ('assigned_to', models.CharField(max_length=100)),
                ('comp_type', models.CharField(choices=[('Webinar', 'Webinar'), ('Trade Show', 'Trade Show'), ('Advertisement', 'Advertisement'), ('Public Relations', 'Public Relations')], max_length=100)),
                ('comp_status', models.CharField(choices=[('Planning', 'Planning'), ('Queued', 'Queued'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], max_length=100)),
                ('audience', models.IntegerField()),
                ('target_size', models.IntegerField()),
                ('sponsor', models.CharField(max_length=100)),
                ('numsent', models.IntegerField()),
                ('budget', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('revenue', models.IntegerField()),
                ('response', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=100)),
                ('sales_count', models.IntegerField()),
                ('actual_sales_count', models.IntegerField()),
                ('ROI', models.IntegerField()),
                ('actual_ROI', models.IntegerField()),
                ('desc', models.TextField()),
            ],
        ),
    ]
