# Generated by Django 2.1.10 on 2019-07-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pro', '0020_addoppurtunity'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddQuotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('oppo_name', models.CharField(max_length=100)),
                ('quote_stage', models.CharField(max_length=100)),
                ('valid_until', models.DateField()),
                ('org_name', models.CharField(max_length=100)),
                ('related_to', models.CharField(max_length=100)),
                ('shipping', models.CharField(max_length=100)),
                ('carrier', models.CharField(choices=[('FedEx', 'FedEx'), ('UPS', 'UPS'), ('USPS', 'USPS'), ('DHL', 'DHL'), ('BlueDart', 'BlueDart')], max_length=100)),
                ('assigned_to', models.CharField(max_length=100)),
                ('cbaf', models.CharField(choices=[('Organization', 'Organization'), ('Related To', 'Related To'), ('Shipping Address', 'Shipping Address')], max_length=100)),
                ('csaf', models.CharField(choices=[('Organization', 'Organization'), ('Related To', 'Related To'), ('Shipping Address', 'Shipping Address')], max_length=100)),
                ('billing_country', models.CharField(choices=[('INDIA', 'INDIA'), ('UNITED STATES', 'UNITED STATES'), ('RUSSIA', 'RUSSIA'), ('CHINA', 'CHINA'), ('AUSTRALIA', 'AUSTRALIA'), ('FRANCE', 'FRANCE')], max_length=100)),
                ('shipping_country', models.CharField(choices=[('INDIA', 'INDIA'), ('UNITED STATES', 'UNITED STATES'), ('RUSSIA', 'RUSSIA'), ('CHINA', 'CHINA'), ('AUSTRALIA', 'AUSTRALIA'), ('FRANCE', 'FRANCE')], max_length=100)),
                ('billing_address', models.CharField(max_length=100)),
                ('shipping_address', models.CharField(max_length=100)),
                ('billing_postal_code', models.IntegerField()),
                ('shipping_postal_code', models.IntegerField()),
            ],
        ),
    ]
