# Generated by Django 2.1.10 on 2019-07-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pro', '0021_addquotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addquotes',
            name='quote_stage',
            field=models.CharField(choices=[('New', 'New'), ('Reviewed', 'Reviewed'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('Rejeted', 'Rejeted')], max_length=100),
        ),
    ]
