# Generated by Django 2.1.10 on 2019-07-26 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pro', '0022_auto_20190726_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=100)),
                ('part_num', models.IntegerField()),
                ('pro_active', models.CharField(max_length=100)),
                ('pro_cat', models.CharField(max_length=100)),
                ('vendor', models.CharField(max_length=100)),
                ('builder', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('support_date', models.DateField()),
                ('supp_end_date', models.DateField()),
                ('serialno', models.IntegerField()),
                ('mfr_part_no', models.IntegerField()),
                ('vendor_part_no', models.IntegerField()),
                ('website', models.URLField()),
                ('price', models.IntegerField()),
                ('commission_rate', models.IntegerField()),
                ('VAT', models.IntegerField()),
                ('sale', models.IntegerField()),
                ('service', models.IntegerField()),
                ('p_cost', models.IntegerField()),
                ('b_type', models.CharField(max_length=100)),
                ('unit', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('demand', models.IntegerField()),
                ('handler', models.CharField(max_length=100)),
                ('p_image', models.FileField(upload_to='pictures')),
                ('desc', models.TextField()),
            ],
        ),
    ]
