# Generated by Django 2.1.10 on 2019-07-26 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pro', '0023_addproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='b_type',
            field=models.CharField(choices=[('One Time', 'One Time'), ('Subscription', 'Subscription')], max_length=100),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='pro_active',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='pro_cat',
            field=models.CharField(choices=[('Hardware', 'Hardware'), ('Software', 'Software'), ('CRM Application', 'CRM Application')], max_length=100),
        ),
    ]
