# Generated by Django 2.1.10 on 2019-07-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pro', '0024_auto_20190726_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('active', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100)),
                ('cat', models.CharField(choices=[('Installation', 'Installation'), ('Support', 'Support'), ('Customization', 'Customization'), ('Migration', 'Migration'), ('Training', 'Training')], max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('sale_date', models.DateField()),
                ('sale_end_date', models.DateField()),
                ('supp_date', models.DateField()),
                ('supp_end_date', models.DateField()),
                ('website', models.URLField()),
                ('price', models.IntegerField()),
                ('commission_rate', models.IntegerField()),
                ('VAT', models.IntegerField()),
                ('sale', models.IntegerField()),
                ('service', models.IntegerField()),
                ('p_cost', models.IntegerField()),
                ('b_type', models.CharField(choices=[('One Time', 'One Time'), ('Subscription', 'Subscription')], max_length=100)),
                ('desc', models.TextField()),
            ],
        ),
    ]
