# Generated by Django 2.1.10 on 2019-07-29 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pro', '0027_auto_20190729_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addinvoices',
            name='num',
            field=models.BigIntegerField(),
        ),
    ]
