# Generated by Django 2.1.10 on 2019-07-29 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pro', '0028_auto_20190729_0831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addinvoices',
            old_name='p_duty',
            new_name='e_duty',
        ),
    ]
