# Generated by Django 2.1.10 on 2019-07-29 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pro', '0029_auto_20190729_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddSalesOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=100)),
                ('oppo', models.CharField(max_length=100)),
                ('q_name', models.CharField(max_length=100)),
                ('p_order', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('assigned_to', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('New', 'New'), ('Approved', 'Approved'), ('Fully Delivered', 'Fully Delivered')], max_length=100)),
                ('s_duty', models.IntegerField()),
                ('p_duty', models.IntegerField()),
                ('cbaf', models.CharField(choices=[('Organization', 'Organization'), ('Related To', 'Related To'), ('Shipping Address', 'Shipping Address')], max_length=100)),
                ('csaf', models.CharField(choices=[('Organization', 'Organization'), ('Related To', 'Related To'), ('Shipping Address', 'Shipping Address')], max_length=100)),
                ('carrier', models.CharField(choices=[('FedEx', 'FedEx'), ('UPS', 'UPS'), ('USPS', 'USPS'), ('DHL', 'DHL'), ('BlueDart', 'BlueDart')], max_length=100)),
                ('org', models.CharField(max_length=100)),
                ('bill_c', models.CharField(choices=[('INDIA', 'INDIA'), ('UNITED STATES', 'UNITED STATES'), ('RUSSIA', 'RUSSIA'), ('CHINA', 'CHINA'), ('AUSTRALIA', 'AUSTRALIA'), ('FRANCE', 'FRANCE')], max_length=100)),
                ('shipp_c', models.CharField(choices=[('INDIA', 'INDIA'), ('UNITED STATES', 'UNITED STATES'), ('RUSSIA', 'RUSSIA'), ('CHINA', 'CHINA'), ('AUSTRALIA', 'AUSTRALIA'), ('FRANCE', 'FRANCE')], max_length=100)),
                ('bpc', models.IntegerField()),
                ('spc', models.IntegerField()),
                ('desc', models.TextField()),
            ],
        ),
    ]
