# Generated by Django 2.1.10 on 2019-07-29 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pro', '0030_addsalesorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addsalesorder',
            old_name='p_duty',
            new_name='e_duty',
        ),
    ]
