# Generated by Django 2.1.10 on 2019-07-29 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pro', '0031_auto_20190729_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddVendors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('p_email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('ass_to', models.CharField(max_length=100)),
                ('cat', models.CharField(max_length=100)),
                ('country', models.CharField(choices=[('INDIA', 'INDIA'), ('UNITED STATES', 'UNITED STATES'), ('RUSSIA', 'RUSSIA'), ('CHINA', 'CHINA'), ('AUSTRALIA', 'AUSTRALIA'), ('FRANCE', 'FRANCE')], max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.IntegerField()),
                ('desc', models.TextField()),
            ],
        ),
    ]
