# Generated by Django 2.1.10 on 2019-07-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pro', '0033_addpurchaseorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpurchaseorder',
            name='desc',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
