# Generated by Django 2.1.10 on 2019-07-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pro', '0035_auto_20190729_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summ', models.TextField()),
                ('c_t', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('pri', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('ass_to', models.CharField(max_length=100)),
                ('channel', models.CharField(max_length=100)),
                ('p_name', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
                ('res', models.TextField()),
                ('cat', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('sla', models.CharField(max_length=100)),
            ],
        ),
    ]
