# Generated by Django 2.1.10 on 2019-07-30 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pro', '0036_addcase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addcase',
            old_name='date',
            new_name='date1',
        ),
    ]
