# Generated by Django 2.1.10 on 2019-07-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pro', '0037_auto_20190730_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcase',
            name='channel',
            field=models.CharField(choices=[('Email', 'Email'), ('Phone', 'Phone'), ('Webform', 'Webform')], max_length=100),
        ),
        migrations.AlterField(
            model_name='addcase',
            name='pri',
            field=models.CharField(choices=[('Urgent', 'Urgent'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=100),
        ),
        migrations.AlterField(
            model_name='addcase',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Assigned', 'Assigned'), ('Resolved', 'Resolved'), ('Waiting', 'Waiting')], max_length=100),
        ),
    ]
