# Generated by Django 2.1.10 on 2019-07-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pro', '0038_auto_20190730_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddServiceContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Support', 'Support'), ('Services', 'Services'), ('Administrative', 'Administrative')], max_length=100)),
                ('pri', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=100)),
                ('status', models.CharField(choices=[('Started', 'Started'), ('New', 'New'), ('In Progress', 'In Progress'), ('Waiting for feedback', 'Waiting for feedback'), ('On hold', 'On hold'), ('Completed', 'Completed')], max_length=100)),
                ('tu', models.CharField(choices=[('Hours', 'Hours'), ('Days', 'Days'), ('Incidents', 'Incidents')], max_length=100)),
                ('uu', models.IntegerField()),
                ('total', models.IntegerField()),
                ('s_d', models.DateField()),
                ('e_d', models.DateField()),
                ('contact', models.CharField(max_length=100)),
            ],
        ),
    ]
