# Generated by Django 2.1.10 on 2019-07-30 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pro', '0039_addservicecontract'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddInternalTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summ', models.TextField()),
                ('i_t', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('New', 'New'), ('Assigned', 'Assigned'), ('Resolved', 'Resolved'), ('Waiting', 'Waiting')], max_length=100)),
                ('pri', models.CharField(choices=[('Urgent', 'Urgent'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=100)),
                ('p_name', models.CharField(max_length=100)),
                ('ass_to', models.CharField(max_length=100)),
                ('channel', models.CharField(choices=[('Email', 'Email'), ('Phone', 'Phone'), ('Webform', 'Webform')], max_length=100)),
                ('res', models.TextField()),
                ('mail', models.EmailField(max_length=254)),
                ('date1', models.DateField()),
                ('sla', models.CharField(max_length=100)),
            ],
        ),
    ]
