# Generated by Django 2.1.10 on 2019-07-30 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pro', '0040_addinternalticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddWorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('New', 'New'), ('Assigned', 'Assigned'), ('Resolved', 'Resolved'), ('Waiting', 'Waiting')], max_length=100)),
                ('org', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('pri', models.CharField(choices=[('Urgent', 'Urgent'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=100)),
                ('service', models.CharField(max_length=100)),
                ('work_desc', models.TextField()),
                ('type', models.CharField(max_length=100)),
                ('loc', models.CharField(choices=[('Onsite', 'Onsite'), ('Remote', 'Remote')], max_length=100)),
                ('s_d', models.DateField()),
                ('t_c', models.TextField()),
            ],
        ),
    ]
