# Generated by Django 2.1.10 on 2019-07-30 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pro', '0041_addworkorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='addworkorder',
            name='loc1',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
