# Generated by Django 2.1.10 on 2019-07-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pro', '0042_addworkorder_loc1'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOurSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_n', models.CharField(max_length=100)),
                ('b_u', models.URLField()),
            ],
        ),
    ]
