# Generated by Django 2.1.10 on 2019-07-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pro', '0043_addoursite'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('lang', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('dep', models.CharField(max_length=100)),
                ('off_phone', models.BigIntegerField()),
                ('mobile', models.BigIntegerField()),
                ('b_hours', models.CharField(choices=[('Standard Business Hours - Asia/Kolkata', 'Standard Business Hours - Asia/Kolkata')], max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('country', models.CharField(choices=[('INDIA', 'INDIA'), ('UNITED STATES', 'UNITED STATES'), ('RUSSIA', 'RUSSIA'), ('CHINA', 'CHINA'), ('AUSTRALIA', 'AUSTRALIA'), ('FRANCE', 'FRANCE')], max_length=100)),
                ('address', models.TextField()),
                ('pincode', models.IntegerField()),
                ('pic', models.ImageField(upload_to='')),
            ],
        ),
    ]
