# Generated by Django 2.1.10 on 2019-07-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pro', '0045_auto_20190730_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addemployee',
            name='pic',
            field=models.ImageField(upload_to='pictures/'),
        ),
    ]
