# Generated by Django 2.1.10 on 2019-07-30 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pro', '0046_auto_20190730_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addemployee',
            old_name='pic',
            new_name='d',
        ),
    ]
