# Generated by Django 2.1.10 on 2019-07-30 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pro', '0047_auto_20190730_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addemployee',
            old_name='mobile',
            new_name='mob',
        ),
    ]
