# Generated by Django 2.1.10 on 2019-07-30 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pro', '0048_auto_20190730_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addemployee',
            name='d',
        ),
    ]
