# Generated by Django 2.1.10 on 2019-07-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pro', '0049_remove_addemployee_d'),
    ]

    operations = [
        migrations.AddField(
            model_name='addemployee',
            name='pic',
            field=models.ImageField(default=0, upload_to='media/'),
            preserve_default=False,
        ),
    ]
