# Generated by Django 2.1.10 on 2019-07-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pro', '0052_auto_20190730_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addemployee',
            name='pic',
            field=models.FileField(upload_to='media'),
        ),
    ]
