# Generated by Django 2.1.10 on 2019-07-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pro', '0053_auto_20190730_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t', models.CharField(max_length=100)),
                ('m', models.CharField(choices=[('Compaign', 'Compaign'), ('Cases', 'Cases'), ('Employees', 'Employees'), ('Service Contacts', 'Service Contacts'), ('Sales Order', 'Sales Order'), ('Vendors', 'Vendors'), ('Services', 'Services'), ('Quotes', 'Quotes'), ('Work Orders', 'Work Orders')], max_length=100)),
                ('desc', models.TextField()),
                ('d_t', models.CharField(max_length=100)),
                ('a', models.CharField(max_length=100)),
            ],
        ),
    ]
