# Generated by Django 2.1.10 on 2019-07-31 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pro', '0054_addtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addemployee',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
